# -*- coding: utf-8 -*-
"""amstron.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d70bhuid_FDQar2f2tmbXNlznqpR_I9p
"""

while True:
    number=input("enter a number please: ")
    num_set=set(number)
    result=0
    numeric={'1','2','3','4','5','6','7','8','9','0'}
    if num_set - numeric == set():
      for i in num_set:
        result+=int(i)**len(num_set)
      break
    else:
      print("It is an invalid entry. Don't use non-numeric, float, or negative values!")

num_int=(int(number))

if result==(num_int):
  print(num_int,"is an Armstrong number")
else:
  print(num_int,"is not an Armstrong number")