# -*- coding: utf-8 -*-
"""assigment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ytH8jqdUsFJY7S425ohNtUZxRVl69Bo4
"""

celsius=int(input("celsius derecesi giriniz:"))
fahren=celsius*1.8+32
print(f"{celsius} celcius {fahren} fahrenheit'a eşittir.")

km=float(input("kilometre giriniz:"))
mil=km*0.621371192
print("{} kilometre {} mile eşittir".format(km,mil))

print("Are you a cigarette addict older than 75 years old?")
age=str(input("yes or no: "))
print("Do you have a severe chronic disease?:")
chronic=str(input("yes or no: "))
print("Is your immune system too weak?")
immune=str(input("yes or no: "))
risk=(age.startswith("yes",0) or chronic.startswith("yes",0) or immune.startswith("yes",0))
if risk==True:
    print("you are in High Risk Group related with")
else:
    print("You can be relax")

print("Is your immune system too weak?")
immune=str(input("yes or no: "))

print(immune.startswith("yes",0) and "no")

city = "SARAJEVO"
text=f"I live in {city.capitalize()}."
print(text)

numbers = [1, 3, 7, 4, 3, 0, 3, 6, 3]

numbers=list()
numbers = [1, 3, 7, 4, 3, 0, 3, 6, 3]
numbers