# -*- coding: utf-8 -*-
"""corona.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13ZuVG6XtGiCt9PWRJhOnBIDAtdrbrUFZ
"""

while True:
    age=str(input("Are you a cigarette addict older than 75 years old?"))
    if age in {"y","ye","yes","no","n"}:
        age=age.lower() in {"y","ye","yes"}
        break
    else:
        print("""this is wrong answer please yes or no""")
while True:
    chronic=str(input("Do you have a severe chronic disease?"))
    if chronic in {"y","ye","yes","no","n"}:
        chronic=chronic.lower() in {"y","ye","yes"}
        break
    else:
        print("""this is wrong answer please yes or no""")
while True:
    immune=str(input("Is your immune system too weak?"))
    if immune in {"y","ye","yes","no","n"}:
        immune=immune.lower() in {"y","ye","yes"}
        break
    else:
        print("""this is wrong answer please yes or no""")
conclusion=(age or chronic or immune)
if conclusion==True:
  print("""You are in risky group""")
else:
  print("""You are not in risky group""")

from IPython.core.display import Math
dir(Math)