# -*- coding: utf-8 -*-
"""fibonacci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OSg2lAoWfpEGBgk4rW8QWJ-404e2VBPW
"""

fibo=[1,1]
for i in range(8):
  fibo.append(fibo[i]+fibo[i+1])
print(fibo)