# -*- coding: utf-8 -*-
"""fizzbuzz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10FXMPfhzAfKU7ycUmZeOsghjrYAZ8Q3Z
"""

for i in range(1,100):
  if i % 3 == 0 and i % 5 != 0:
  
    print("fizz")

  elif i % 5 == 0 and i % 3 != 0:

    print("buzz")
  
  elif i % 3 == 0 and i % 5 == 0:

    print("fizzbuzz")
  
  else:

    print(i)