# -*- coding: utf-8 -*-
"""Front-Back Char-assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1da7iTXNtcnKpSDLEDKBXJP-lNGcwlEKU
"""

def front_back(word):
    if len(word)==1:
      return word
    else:
      a=list(word)
      a.insert(0,a[-1])
      a.pop()
      a.append(a[1])
      a.pop(1)
      a="".join(a)
      return a
front_back("word")