# -*- coding: utf-8 -*-
"""Letter_count.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s9QM287GY12AWjRh-fGv5CsreJHYE4yE
"""

sentences=input("pass a sencentes: ")
Dict1={}
for i in sentences:
  Dict1[i]=sentences.count(i)
print(Dict1)