# -*- coding: utf-8 -*-
"""max_num_without_max().ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18tcVD7xo61o62TQ4OjBNiEsx_s0hcJPF
"""

list_num=[]

for i in range(1,6):
  num=int(input(f"Please enter {i}th number :"))
  list_num.append(num)
 
max_num=int()
for i in list_num:
  if i > max_num:
    max_num=i
print(f"max_num is {max_num}")