# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1newkeO_mXMEvun_HHhdexj9PZ9LCmzeO
"""

def missing_char(word, n):
    a=list(word)
    a.pop(n)
    b="".join(a)
    return b
missing_char("deneme",3)