# -*- coding: utf-8 -*-
"""most_frequent_counter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1622Ti_PBweQLoCJOpr40ER3RbVv4xK5J
"""

import collections
numbers = [1, 3, 7, 4, 3, 0, 3, 6,3]
most_frequent=collections.Counter(numbers).most_common(1)
print(most_frequent)
list(most_frequent)
print(f"the most frequent number is {most_frequent[0][0]} and it was {most_frequent[0][1]} times repeated")
print(numbers)