# -*- coding: utf-8 -*-
"""not_string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VYjhxbNOsGSiK2kotJDsPZZtFixEcPfL
"""

def not_string(word):
    if word.startswith("not"):
        print(word)
    else:
        print("not "+word)
not_string("selam")