# -*- coding: utf-8 -*-
"""open-read.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P2OKTkjus5s5O52M7DXZTf4XFIO5q8D2
"""

try:
    f = open('myfile.txt')
    print(f.read())
except:
    print("Something went wrong")
finally:
    f. close()

"""# Yeni Bölüm"""