# -*- coding: utf-8 -*-
"""prime_num_n.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xnl7tKbCJZJ1LRvSDKR49nazCml1qIsF
"""

n=int(input("enter a number pls : "))
prime_list=[]
for sayı in range(2,n):
  counter=0
  for i in range(2,sayı):
    if sayı % i==0:
      counter += 1 
  if counter ==0:
    prime_list.append(sayı)
print(f"From 1 to {n} prime_number_list is {prime_list}")