# -*- coding: utf-8 -*-
"""vowelConsecutive.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vt3hYoYKYEpRzh2vMx8lb6ZMgFe8VR3_
"""

word=list(input("please enter a string "))
vowel=["a","e","ı","i","o","ö","u","ü"]
count=0
for i in word:
  if i in vowel:
    count +=1
    if count>1:
      break
  else:
    count=0
if count>1:
  print("Positive")
else:
  print("Negative")